<!DOCTYPE html>
<html>
<head>
    <title>Laporan Tasks - {{ now()->format('d F Y') }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            font-size: 12px;
            line-height: 1.5;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px; 
            border-bottom: 3px solid #3b82f6;
            padding-bottom: 15px;
        }
        h1 { 
            color: #1e40af; 
            margin: 0;
        }
        .subtitle {
            color: #64748b;
            font-size: 14px;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px;
        }
        th, td { 
            border: 1px solid #94a3b8; 
            padding: 10px 8px; 
            text-align: left;
        }
        th { 
            background-color: #1e40af; 
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .status {
            padding: 4px 10px;
            border-radius: 20px;
            font-size: 11px;
            text-align: center;
        }
        .completed { background-color: #86efac; color: #166534; }
        .progress { background-color: #93c5fd; color: #1e40af; }
        .overdue { background-color: #fca5a5; color: #991b1b; }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: #64748b;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LAPORAN TASK MANAGEMENT</h1>
        <p class="subtitle">TaskFlow - PT. Your Company</p>
        <p>{{ now()->format('d F Y H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="18%">Kode Task</th>
                <th width="22%">Nama Tugas</th>
                <th width="18%">Project</th>
                <th width="12%">Client</th>
                <th width="12%">Deadline</th>
                <th width="8%">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tasks as $index => $task)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $task->code ?? '-' }}</td>
                <td><strong>{{ $task->name }}</strong></td>
                <td>{{ $task->project->name ?? '-' }}</td>
                <td>{{ $task->client ?? '-' }}</td>
                <td>{{ $task->ended_at ? $task->ended_at->format('d M Y') : '-' }}</td>
                <td>
                    @if($task->status == 'completed')
                        <span class="status completed">Selesai</span>
                    @elseif($task->status == 'on_progress')
                        <span class="status progress">Progress</span>
                    @elseif($task->status == 'overdue')
                        <span class="status overdue">Overdue</span>
                    @else
                        <span class="status">{{ ucfirst($task->status) }}</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by TaskFlow System • Total Tasks : {{ $tasks->count() }}</p>
    </div>
</body>
</html>